### ISSUE TITLE
Failed on atom 1.21.1 x64

### ISSUE THREAD

**Issue by arg3ni5** [dbslone/git-tabs#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [git-tabs](https://github.com/dbslone/git-tabs) package 0.2.0

### Stack Trace

Failed to activate the git-tabs package

```
At Illegal argument undefined

Error: Illegal argument undefined
    at module.exports (/packages/git-tabs/node_modules/md5/md5.js:152:13)
    at TabManager.updateRepo (/packages/git-tabs/lib/tab-manager.js:28:16)
    at /packages/git-tabs/lib/tab-manager.js:17:12)
    at Object.activate (/packages/git-tabs/lib/git-tabs.js:9:23)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.21.1/resources/app/src/package-manager.js:690:42)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.21.1/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.21.1/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -1:46.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
angularjs 0.4.0 
angularjs-snippets 0.10.18 
api-docs 0.0.6 
atom-beautify 0.30.5 
atom-bootstrap3 1.2.12 
atom-browser 0.53.0 
atom-js-console 1.2.2 
atom-material-syntax 1.0.7 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.5 
atom-sync-packages 1.1.0 
atom-terminal 0.8.0 
atom-ternjs 0.18.3 
busy-signal 1.4.3 
chary-tree-view 0.2.13 
clipboard-plus 0.5.1 
code-peek 1.4.21 
color-picker 2.2.5 
color-tabs 0.1.8 
css-snippets 1.1.0 
directory-color 0.3.0 
docblockr 0.11.0 
emmet 2.4.3 
file-icons 2.1.13 
firacode 0.3.0 
git-log 0.4.1 
git-tabs 0.2.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 2.0.0 
linter-htmlhint 1.3.4 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
livereload 0.4.4 
merge-conflicts 1.4.5 
min-ui 0.0.4 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
monokai-seti 0.9.0 
open-recent 5.0.0 
open-terminal-here 2.3.1 
pigments 0.40.2 
pinned-tabs 1.3.0 
platformio-ide-terminal 2.7.0 
recent-files-fuzzy-finder 0.3.2 
remember-folds 0.3.0 
seti-syntax 1.1.3 
seti-ui 1.9.0 
solarized-seti-ui 0.8.6 
sync-settings 0.8.3 
todo-show 2.1.0 
tree-view-autoresize 2.2.0 
tree-view-filter 0.5.3 
tree-view-git-status 1.4.0 
tree-view-panes 0.3.7 
xatom-ui 0.2.0 
```

**Comment by avaly** [comment]
https://github.com/dbslone/git-tabs/pull/10 should fix this issue.

**Comment by dbslone** [comment]
Closing issue since @avaly PR resolves the issue
