### ISSUE TITLE
Failed to activate the git-tabs package

### ISSUE THREAD

**Issue by johnyxz** [dbslone/git-tabs#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [git-tabs](https://github.com/dbslone/git-tabs) package 0.1.2

### Stack Trace

Failed to activate the git-tabs package

```
At Cannot read property 'getShortHead' of null

TypeError: Cannot read property 'getShortHead' of null
    at /packages/git-tabs/lib/tab-manager.js:14:30)
    at Object.activate (/packages/git-tabs/lib/git-tabs.js:21:23)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:826:28
```

### Commands

```
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-clock 0.1.7 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.10 
context-git 0.15.8 
git-commit 1.5.3 
git-control 0.9.0 
git-controlhub 0.4.0 
git-go 1.0.5 
git-grep 0.9.0 
git-log 0.4.1 
git-plus 7.8.0 
git-plus-plus 1.1.0 
git-projects 1.17.0 
git-status 0.3.4 
git-tabs 0.1.2 
git-tools 0.4.1 
Hydrogen 1.12.1 
open-git-modified-files 0.2.4 
qolor 0.4.1 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.3.1 
```

**Comment by dbslone** [comment]
thanks @johnyxz I will look into the issue
